services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1436:1433"
    volumes:
      - sqldata:/var/lib/mssql/data

volumes:
  sqldata:
